<?php

return [
    'templates' => [
        'partials/left.blade.php' => 'Sol Kenar Cubugu',
        'partials/right.blade.php' => 'Sag Kenar Cubugu',
        'layouts/app.blade.php' => 'Uygulama Yerlesimi',
        'layouts/guest.blade.php' => 'Misafir Yerlesimi',
        'blog/layout.blade.php' => 'Blog Yerlesimi',
        'blog/show.blade.php' => 'Gonderi Detayi',
        'blog/categories.blade.php' => 'Kategoriler',
        'blog/categories/categories-show.blade.php' => 'Kategori Detayi',
        'blog/tags.blade.php' => 'Etiketler',
        'messages/index.blade.php' => 'Mesajlar',
        'messages/show.blade.php' => 'Mesaj Konusmasi',
        'messages/settings.blade.php' => 'Mesaj Ayarlari',
        'blog/post-card.blade.php' => 'Gonderi Karti',
        'blog/post/comments.blade.php' => 'Gonderi Yorumlari',
        'blog/reaction.blade.php' => 'Tepki Secici',
        'blog/post/reactions.blade.php' => 'Gonderi Tepkileri',
        'blog/create.blade.php' => 'Gonderi Olustur',
        'blog/edit.blade.php' => 'Gonderi Duzenle',
        'blog/repost-create.blade.php' => 'Yeniden Paylasim Olustur',
        'blog/categories/edit.blade.php' => 'Kategori Duzenle',
        'auth/login.blade.php' => 'Giris',
        'auth/register.blade.php' => 'Kayit',
        'profile/show.blade.php' => 'Profil',
        'dashboard.blade.php' => 'Panel',
        'components/mobile-bottom-nav.blade.php' => 'Mobil Alt Menu',
        'components/install-layout.blade.php' => 'Kurulum Yerlesimi',
        'video_player.blade.php' => 'Video Oynatici',
    ],
    'backup_dir' => 'blade-backups',
    'max_backups' => 20,
];
